package Minerals;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
//ensure abstract class can be analysed by json,this part is generated by AI
@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        include = JsonTypeInfo.As.PROPERTY,
        property = "name"
)
@JsonSubTypes({
        @JsonSubTypes.Type(value = Gold.class, name = "gold"),
        @JsonSubTypes.Type(value = Diamond.class, name = "diamond"),
        @JsonSubTypes.Type(value = Stone.class, name = "stone")
})
public abstract class Mineral {
    protected Long id;
    protected String name;
    protected int value;
    protected int weight;
    public Mineral(Long id, String name, int value, int weight) {
        this.id = id;
        this.name = name;
        this.value = value;
        this.weight = weight;
    }
    public Mineral() {}
    public int getWeight() {
        return weight;
    }

    public void setWeight(int weight) {
        this.weight = weight;
    }

    public int getValue() {
        return value;
    }

    public void setValue(int value) {
        this.value = value;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public abstract int calculateValue();
}

